return {
	-- "zenbones-theme/zenbones.nvim",
	-- lazy = false,
	-- priority = 1000,
	-- config = function()
	-- 	vim.g.bones_compat = 1
	-- 	vim.g.zenbones_transparent_background = 0
	-- 	vim.g.zenbones_solid_line_nr = 1
	-- 	vim.g.zenbones_italic_comments = 0
	-- 	vim.g.zenbones_lighten_line_nr = 10000000000
	-- 	vim.g.zenbones_solid_float_border = true
	-- 	vim.g.colorize_diagnostic_underline_text = true
	-- 	ColorMyPencils("rosebones")
	-- 	DisableItalic()
	-- 	CMD("hi DiagnosticUnderlineHint gui=underline")
	-- 	CMD("hi DiagnosticUnderlineInfo gui=underline")
	-- 	CMD("hi DiagnosticUnderlineWarn gui=underline")
	-- 	CMD("hi DiagnosticUnderlineError gui=underline")
	-- 	CMD("hi @markup.link gui=none")
	-- end,
}
