return {
	-- 	"jesseleite/nvim-noirbuddy",
	-- 	dependencies = { { "tjdevries/colorbuddy.nvim" } },
	-- 	lazy = false,
	-- 	priority = 1000,
	-- 	config = function()
	-- 		require("noirbuddy").setup({
	-- 			preset = "minimal",
	-- 			colors = {
	-- 				-- primary = "#D5A6A8",
	-- 				-- secondary = "#FADADD"
	-- 			},
	-- 			styles = {
	-- 				italic = false,
	-- 				bold = true,
	-- 				underline = true,
	-- 				undercurl = false,
	-- 			},
	-- 		})
	-- 		ColorMyPencils("noirbuddy")
	-- 		DisableItalic()
	-- 	end,
}
