-- 	require("jabs").setup({
-- 		position = "center",
-- 		border = "single",
-- 		sort_mru = true,
-- 		symbols = {
-- 			current = "C", -- default 
-- 			split = "S", -- default 
-- 			alternate = "A", -- default 
-- 			hidden = "H", -- default ﬘
-- 			locked = "L", -- default 
-- 			ro = "R", -- default 
-- 			edited = "E", -- default 
-- 			terminal = "T", -- default 
-- 			default_file = "D", -- Filetype icon if not present in nvim-web-devicons. Default 
-- 			terminal_symbol = ">_", -- Filetype icon for a terminal split. Default 
-- 		},
-- 		keymap = {
-- 			h_split = "s",
-- 			v_split = "v",
-- 			close = "dd",
-- 		},
-- 	})
-- 	MAP("n", "<leader>fb", ":JABSOpen<CR>")
